# Generated by Django 4.2.3 on 2023-08-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=10)),
                ('role', models.CharField(choices=[('SALE', '带货'), ('PERFORMANCE', '才艺'), ('KNOWLEDGE', '知识'), ('AFFECTION', '情感')], max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education', models.CharField(blank=True, choices=[('DOCTOR', '博士'), ('MASTER', '硕士'), ('BACHELOR', '本科'), ('JUNIOR_COLLEGE', '大专'), ('HIGH_SCHOOL', '高中'), ('VOCATIONAL_SCHOOL', '中专'), ('OTHER', '其他')], max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('personality', models.CharField(blank=True, max_length=30, null=True)),
                ('habit', models.CharField(blank=True, max_length=50, null=True)),
                ('hobby', models.CharField(blank=True, max_length=50, null=True)),
                ('advantage', models.CharField(blank=True, max_length=50, null=True)),
                ('speaking_style', models.CharField(blank=True, max_length=50, null=True)),
                ('audience_type', models.CharField(blank=True, max_length=30, null=True)),
                ('world_view', models.TextField(blank=True, max_length=400, null=True)),
                ('personal_statement', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
