# Generated by Django 4.2.3 on 2023-09-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_image_icon_url_alter_image_rel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='icon_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='rel_url',
            field=models.URLField(max_length=1000),
        ),
    ]
