# Generated by Django 4.2.3 on 2023-09-15 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0009_environment_userenvironment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOrder',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=15)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('paid_datetime', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentOrder',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=15)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('paid_datetime', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
