# Generated by Django 4.2.3 on 2023-09-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_imageorder_environmentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentorder',
            name='paid_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageorder',
            name='paid_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
