# Generated by Django 4.2.3 on 2023-09-18 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material', '0012_liveconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveconfig',
            name='interaction_types',
        ),
        migrations.AlterField(
            model_name='liveconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
